services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/main/php:/var/www/html/src/main/php
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"