services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"