services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.apache
    volumes:
      - ./src/main/php:/var/www/html/src/main/php
      - ./src/main/resources:/var/www/html/src/main/resources
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - whatever

  database:
    image: mysql/mysql-server:8.0.32
    ports:
      - "3800:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - whatever

networks:
  whatever:
    driver: bridge