services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.apache
    volumes:
      - ./src/main/php:/var/www/html/src/main/php
      - ./src/main/resources:/var/www/html/src/main/resources
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - whatever

  database:
    image: mariadb:11.6.2
    ports:
      - "3800:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_ROOT_HOST: ${MYSQL_ROOT_HOST}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - whatever
    volumes:
      - mariadatavolume:/var/lib/mysql

volumes:
  mariadatavolume:

networks:
  whatever:
    driver: bridge