name: CI-coverage

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          php_version: 8.3

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3800
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0.32'
          mysql root password: ${{ secrets.MYSQLPASSWORD }}

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 -P 3800 --password=${{ secrets.MYSQLPASSWORD }} --silent; do
            sleep 1
          done

      - name: Create Connection Data config
        run: |
          echo "host = localhost" >> config/mysql/connection-data.ini
          echo "port = 3800" >> config/mysql/connection-data.ini
          echo "database = testing_db" >> config/mysql/connection-data.ini
          echo "username = ${{ secrets.MYSQLUSER }}" >> config/mysql/connection-data.ini
          echo "password = ${{ secrets.MYSQLPASSWORD }}" >> config/mysql/connection-data.ini

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          php_version: 8.3
          version: 9.5.26
          php_extensions: pdo_mysql opcache zip xdebug
          bootstrap: vendor/autoload.php
          configuration: src/test/phpunit.xml
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
      - name: Generate test coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          coverage_badge_path: 'badge-coverage.svg'
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
