name: CI-coverage

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3800
          container port: 3307
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0.32'
          mysql database: 'testing_db'
          mysql root password: ${{ secrets.RootPassword }}
          mysql user: 'developer'
          mysql password: ${{ secrets.DatabasePassword }}

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.5.26
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: src/test/phpunit.xml
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
      - name: Generate test coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          coverage_badge_path: 'badge-coverage.svg'
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
